#Global configuration
spring.application.name=TradeIO5
#for dev mod only
spring.thymeleaf.cache=false 

#Tomcat configuration
server.port=8080

#Logging 
logging.level.root=DEBUG
# output to a file // Injected in logback-spring.xml that add .log
logging.file.name=logs/${spring.application.name}

#Database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/tradeio5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
